enum Gender {
    Male = 'male',
    Female = 'female',
}

export const Alums = [
    {
        name: 'Richa',
        designation_a: 'Software Developer, JP Morgan & Chase',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Female,
    },
    {
        name: 'Chirag Baghasingh',
        designation_a: 'Ethereum Protocol Fellow',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Movish Verma',
        designation_a: 'Software Developer, SAP Labs',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Neerav Chittora',
        designation_a: 'Software Developer, Google',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Pooja Patel',
        designation_a: 'Software Developer, Microsoft',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Female,
    },
    {
        name: 'Parthsarthi Mishra',
        designation_a: 'Software Engineer, Qualcomm',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Kamal Sharma',
        designation_a: '',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Yash Bhanushali',
        designation_a: '',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
    {
        name: 'Jatin Agarwal',
        designation_a: '',
        designation_b: '',
        image: '',
        github: '',
        twitter: '',
        linkedin: '',
        gender: Gender.Male,
    },
]