enum Gender {
    Male = 'male',
    Female = 'female',
}

export const Alums = [
    {
        name: 'Richa',
        designation_a: 'Software Developer, JP Morgan & Chase',
        image: '/team_images/richa.jpg',
        github: 'https://github.com/Richa-iitr/',
        twitter: 'https://x.com/richa3112/',
        linkedin: 'https://www.linkedin.com/in/richa-3087a120a/',
        gender: Gender.Female,
    },
    {
        name: 'Chirag Baghasingh',
        designation_a: 'Ethereum Protocol Fellow',
        image: '/team_images/chirag.jpg',
        github: 'https://github.com/chirag-bgh/',
        twitter: 'https://x.com/0xstrider_/',
        linkedin: 'https://www.linkedin.com/in/chirag-baghasingh-753b711b9/',
        gender: Gender.Male,
    },
    {
        name: 'Movish Verma',
        designation_a: 'Software Developer, SAP Labs',
        image: '/team_images/movish.jpg',
        github: '',
        twitter: 'https://x.com/movish_v/',
        linkedin: 'https://www.linkedin.com/in/movishverma/',
        gender: Gender.Male,
    },
    {
        name: 'Neerav Chittora',
        designation_a: 'Software Developer, Google',
        image: '/team_images/neerav.jpeg',
        github: 'https://github.com/neerav1234/',
        twitter: 'https://x.com/NeeravChittora/',
        linkedin: 'https://www.linkedin.com/in/neerav-chittora-a470071ba/',
        gender: Gender.Male,
    },
    {
        name: 'Pooja Patel',
        designation_a: 'Software Developer, Microsoft',
        image: '/team_images/pooja.jpg',
        github: '',
        twitter: 'https://x.com/0xpooja6/',
        linkedin: 'https://www.linkedin.com/in/pooja-patel-512b29227/',
        gender: Gender.Female,
    },
    {
        name: 'Parthsarthi Mishra',
        designation_a: 'Software Engineer, Qualcomm',
        image: '/team_images/parthsarthi.jpg',
        github: '',
        twitter: '',
        linkedin: 'https://www.linkedin.com/in/parthsarthi-mishra-86a30814b/',
        gender: Gender.Male,
    },
    {
        name: 'Kamal Sharma',
        designation_a: '',
        image: '/team_images/kamal.jpg',
        github: 'https://github.com/kamal3951/',
        twitter: 'https://x.com/0xmaxlad/',
        linkedin: 'https://www.linkedin.com/in/kamalsharma01/',
        gender: Gender.Male,
    },
    {
        name: 'Yash Bhanushali',
        designation_a: '',
        image: '/team_images/yash.jpg',
        github: '',
        twitter: 'https://x.com/Y_ash19/',
        linkedin: 'https://www.linkedin.com/in/yash-bhanushali-a34a2a22a/',
        gender: Gender.Male,
    },
    {
        name: 'Jatin Agarwal',
        designation_a: '',
        image: '/team_images/jatin.jpg',
        github: '',
        twitter: 'https://x.com/_jatinagarwal/',
        linkedin: 'https://www.linkedin.com/in/jatinagarwal69/',
        gender: Gender.Male,
    },
]
