export const BlogPosts = [
    {
        id: 1,
        title: 'Lessons in Async Rust from Building BraidPool',
        description: 'A deep dive into real-world async programming patterns and Tokio best practices',
        content: ``,
        author: 'Abdullah Azeem',
        date: 'Aug 22, 2025',
        slug: 'braidpool-async-lessons',
        tags: ['Research'],
        link: 'https://abd-aze.github.io/blog/braidpool-async-lessons',
    },
    {
        id: 2,
        title: 'Building Decentralized Peer Discovery with libp2p',
        description: 'How Braidpool leverages libp2p for robust P2P networking',
        content: ``,
        author: 'Abdullah Azeem',
        date: 'Jul 03, 2025',
        slug: 'libp2p-peer-discovery',
        tags: ['Research'],
        link: 'https://abd-aze.github.io/blog/libp2p-peer-discovery',
    },
    {
        id: 3,
        title: '3-Slot Finality: The Next Evolution in Ethereum Consensus',
        description: "How a breakthrough in consensus design could reduce Ethereum's finality time from minutes to seconds",
        content: ``,
        author: 'Utsav Sharma',
        date: 'Aug 9, 2025',
        slug: '3-slot-finality',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/3-slot-finality-the-next-evolution',
    },
    {
        id: 4,
        title: "Understanding Ethereum's RANDAO Mechanism",
        description: 'Exploring How Randomness Secures the Beacon Chain and the Ongoing Efforts to Strengthen It Against Manipulation',
        content: ``,
        author: 'Utsav Sharma',
        date: 'Apr 27, 2025',
        slug: 'randao-mechanism',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/understanding-ethereums-randao-mechanism',
    },
    {
        id: 5,
        title: "How Light Clients Track Ethereum's Consensus Layer",
        description: 'Building Selene: Golang light client inspired from Helios.',
        content: ``,
        author: 'Sambhav Jain',
        date: 'Apr 23, 2025',
        slug: 'light-clients-ethereum-consensus',
        tags: ['Research'],
        link: 'https://hackmd.io/@JdxQkWkdTHWIIEkki2_axQ/rJDKd-ryxe',
    },
    {
        id: 6,
        title: 'Understanding BLS Signatures in Ethereum',
        description: "As Ethereum transitioned from Proof of Work to Proof of Stake with the beacon chain, the consensus protocol faced a critical scalability bottleneck handling hundreds of thousands of validator signatures per epoch.",
        content: ``,
        author: 'Veer Chaurasia',
        date: 'Apr 22, 2025',
        slug: 'bls-signatures-ethereum',
        tags: ['Research'],
        link: 'https://0xpsuedo.substack.com/p/understanding-bls-signatures-in-ethereum',
    },
    {
        id: 7,
        title: 'Hash-Based Signatures: A Quantum-Resistant Future?',
        description: 'Beyond RSA & ECDSA: The Future of Digital Signatures in a Post-Quantum World',
        content: ``,
        author: 'Utsav Sharma',
        date: 'Apr 1, 2025',
        slug: 'hash-based-signatures',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/hash-based-signatures-a-quantum-resistant',
    },
    {
        id: 8,
        title: 'Elliptic Curve Digital Signature Algorithm (ECDSA)',
        description: 'One of the most significant aspects of bitcoin, or in general any cryptographic currency, is its use of digital signatures. In digital currency, ownership is established by a piece of digital data as opposed to...',
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Apr 4, 2023',
        slug: 'ecdsa',
        tags: ['Research'],
        link: 'https://medium.com/@blocsoc.acm/ecdsa-26402064fd34',
    },
    {
        id: 9,
        title: 'Gas Optimization in Smart Contracts',
        description: 'As a blockchain scales , scarce resources may become too expensive resulting in only wealthier people being able to participate thereby reducing decentrality , and this in-turn will...',
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Sep 8, 2022',
        slug: 'gas-optimization',
        tags: ['Research'],
        link: 'https://medium.com/@blocsoc.acm/gas-optimization-in-smart-contracts-d4bd508dd361',
    },
    {
        id: 10,
        title: 'Unfolding the Terra-Luna crash',
        description: "Terra is a proof-of-stake layer 1 blockchain built using the Cosmos SDK, propagating the idea of \"decentralized money\". According to Terra's white paper, the founders' goal was to...",
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Jun 17, 2022',
        slug: 'terra-luna',
        tags: ['Research', 'News'],
        link: 'https://medium.com/@blocsoc.acm/unfolding-the-terra-luna-crash-b7e81beefab',
    }
]
